version: '3'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./front/app:/app
      - front_node_modules:/app/node_modules
    tty: true
    #restart: on-failure
    working_dir: /app

volumes:
  front_node_modules: